### 기초통계분석용 report

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
football_df = pd.read_csv('../data/football_eda.csv', encoding='utf-8-sig') # 분석용 데이터
football_df

,Name,Age,Nation,Position,Club,League,Confederation,MarketValue,Field,OVR,PAC,SHO,PAS,DRI,DEF,PHY
0,Aaron Cresswell,35,England,Left_Back,Stoke City,Championship,UEFA,8,DF,74,59,59,74,74,75,62
1,Aaron Herrera,28,Guatemala,Right_Back,D.C. United,MLS,CONCACAF,32,DF,71,71,49,69,70,67,75
2,Aaron Hickey,23,Scotland,Right_Back,Brentford FC,PremierLeague,UEFA,162,DF,76,74,54,70,74,74,68
3,Aaron Long,32,United States,Centre_Back,Los Angeles FC,MLS,CONCACAF,24,DF,70,78,39,54,60,68,80
4,Aaron Molinas,24,Argentina,Attacking_Midfielder,Defensa y Justicia,Liga_Profesional,CONMEBOL,49,MF,72,73,57,72,76,51,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827,Zidane Iqbal,22,Iraq,Central_Midfielder,FC Utrecht,Eredivisie,AFC,65,MF,63,68,58,61,70,52,56
2828,Zidan Sertdemir,20,Denmark,Central_Midfielder,FC Nordsjaelland,Danish_Superligaen,UEFA,32,MF,64,68,56,64,67,49,58
2829,Zinedine Machach,29,France,Attacking_Midfielder,Melbourne Victory,A_League,UEFA,11,MF,70,72,66,67,74,42,79
2830,Zion Suzuki,22,Japan,Goalkeeper,Parma Calcio 1913,Serie_A,AFC,325,GK,71,71,68,71,76,56,67
2831,Zito Luvumbo,23,Angola,Striker,Cagliari Calcio,Serie_A,CAF,81,FW,73,87,70,66,78,46,66

In [3]:
football_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2832 entries, 0 to 2831
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           2832 non-null   object
 1   Age            2832 non-null   int64
 2   Nation         2832 non-null   object
 3   Position       2832 non-null   object
 4   Club           2832 non-null   object
 5   League         2832 non-null   object
 6   Confederation  2832 non-null   object
 7   MarketValue    2832 non-null   int64
 8   Field          2832 non-null   object
 9   OVR            2832 non-null   int64
 10  PAC            2832 non-null   int64
 11  SHO            2832 non-null   int64
 12  PAS            2832 non-null   int64
 13  DRI            2832 non-null   int64
 14  DEF            2832 non-null   int64
 15  PHY            2832 non-null   int64
dtypes: int64(9), object(7)
memory usage: 354.1+ KB

In [4]:
football_df.nunique()

Name             2829
Age                24
Nation            116
Position           11
Club              496
League             47
Confederation       6
MarketValue        93
Field               4
OVR                42
PAC                65
SHO                71
PAS                60
DRI                57
DEF                72
PHY                52
dtype: int64

In [5]:
print("포지션별 선수 수:")
print(football_df['Field'].value_counts())

print("\n세부 포지션별 선수 수:")
print(football_df['Position'].value_counts())

포지션별 선수 수:
Field
DF    903
MF    897
FW    618
GK    414
Name: count, dtype: int64

세부 포지션별 선수 수:
Position
Centre_Back             521
Striker                 431
Goalkeeper              414
Central_Midfielder      374
Defensive_Midfielder    259
Attacking_Midfielder    228
Right_Back              202
Left_Back               180
Right_Winger             98
Left_Winger              89
Side_Midfielder          36
Name: count, dtype: int64

In [6]:
print("국가별 선수 수 Top 10:")
print(football_df['Nation'].value_counts().head(10))

print("\n대륙(연맹)별 선수 수:")
print(football_df['Confederation'].value_counts())

국가별 선수 수 Top 10:
Nation
England          188
France           151
Argentina        150
Germany          131
United States    131
Spain            120
Brazil           112
Netherlands      106
Italy            103
Denmark           93
Name: count, dtype: int64

대륙(연맹)별 선수 수:
Confederation
UEFA        1664
CONMEBOL     366
CAF          322
CONCACAF     229
AFC          206
OFC           45
Name: count, dtype: int64

In [6]:
print("등록 선수가 가장 많은 리그 TOP 20:")
print(football_df['League'].value_counts().head(20))

등록 선수가 가장 많은 리그 TOP 20:
League
PremierLeague           385
Serie_A                 235
MLS                     199
Bundesliga              191
Ligue1                  168
LaLiga                  148
Championship            144
Eredivisie              104
SuperLig                100
Jupiler_ProLeague        96
Liga_Profesional         90
Scottish_Premiership     79
Austria_Bundesliga       77
Swiss_SuperLeague        77
Danish_Superligaen       77
Liga_Portugal            76
A_League                 73
SuperLeague1             71
Saudi_ProLeague          70
K_League1                53
Name: count, dtype: int64

In [4]:
print("\n등록 선수가 가장 많은 팀 TOP 20:")
print(football_df['Club'].value_counts().head(20))

등록 선수가 가장 많은 팀 TOP 20:
Club
Chelsea FC                 33
Manchester City            26
RB Leipzig                 24
Liverpool FC               24
Manchester United          22
AC Milan                   22
Inter Milan                22
Tottenham Hotspur          22
Brighton & Hove Albion     22
Crystal Palace             21
Arsenal FC                 21
Paris Saint-Germain        20
Red Bull Salzburg          20
Brentford FC               20
SSC Napoli                 20
Celtic FC                  19
Real Madrid                19
FC Barcelona               19
Wolverhampton Wanderers    19
Rangers FC                 18
Name: count, dtype: int64

In [ ]:
print("MarketValue_krw 요약 통계:")
print(football_df['MarketValue_krw'].describe())

print("포지션별 평균 능력치:")
print(football_df.groupby('Field')[['OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].mean().round(2))

print("OVR(전체 능력치) 상위 5명:")
print(football_df[['Name', 'Field', 'OVR']].sort_values(by='OVR', ascending=False).head(5))

# OVR 기준 상위 10명
top_players = football_df.sort_values('OVR', ascending=False).head(10)
top_players[['Name','Age','Field','OVR','Billion_KRW']]



import pandas as pd

# 1. 데이터 형태 및 컬럼 확인
print("🔹 데이터프레임 기본 정보:")
football_df.info()

print("\n🔹 컬럼별 결측값 개수:")
print(football_df.isnull().sum())

print("\n🔹 데이터프레임 크기 (행, 열):")
print(football_df.shape)

print("\n🔹 데이터프레임 컬럼 목록:")
print(football_df.columns.tolist())

# 2. 수치형 컬럼 요약 통계
print("\n🔹 수치형 컬럼 describe:")
print(football_df.describe())

# 3. 범주형 컬럼 요약 통계
print("\n🔹 범주형 컬럼 describe:")
print(football_df.describe(include='object'))

# 4. 중복 데이터 확인
print("\n🔹 중복 행 개수:", football_df.duplicated().sum())

# 5. 국가별 선수 수 상위 10개
print("\n🔹 국가별 선수 수 (Top 10):")
print(football_df['Nation'].value_counts().head(10))

# 6. 리그별 선수 수 상위 10개
print("\n🔹 리그별 선수 수 (Top 10):")
print(football_df['League'].value_counts().head(10))

# 7. 포지션(Field)별 평균 능력치
print("\n🔹 포지션별 평균 능력치:")
print(football_df.groupby('Field')[['OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].mean())

# 8. 대륙(Confederation)별 선수 수
print("\n🔹 대륙별 선수 수:")
print(football_df['Confederation'].value_counts())

# 9. 시장가치(Billion_KRW) 기준 상위 5명
print("\n🔹 시장가치 상위 5명:")
print(football_df[['Name', 'Billion_KRW']].sort_values(by='Billion_KRW', ascending=False).head(5))

# 10. OVR 기준 상위 5명
print("\n🔹 OVR 기준 상위 5명:")
print(football_df[['Name', 'OVR', 'Club', 'Nation']].sort_values(by='OVR', ascending=False).head(5))